[theme]
base="light"
primaryColor="#66913E"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#173D4A" # O #333333 si prefieres que todo el texto sea más oscuro
font="sans serif"

[logger]
level = "info"

[server]
headless = true
runOnSave = true
