[theme]
base="light"
primaryColor="#66913E"                # COLOR_VERDE_ECO
backgroundColor="#FFFFFF"             # Fondo blanco
secondaryBackgroundColor="#F0F2F6"    # Gris claro para elementos secundarios
textColor="#173D4A"                   # COLOR_AZUL_ECO para texto principal
font="sans serif"

[logger]
level = "info"                        # Opciones: "error", "warning", "info", "debug"

[server]
headless = true                       # Recomendado para despliegues
runOnSave = true                      # Útil para desarrollo local, recarga automática
